---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Software installation and configuration
    - name: module-02
      label: Inspecting container access and SELinux policies
    - name: module-03
      label: Generating SELinux container policies with Udica
    - name: module-04
      label: Verifying the SELinux container policies with Udica
    - name: module-05
      label: Re-inspect the running container
tabs:
  - name: ">_ Terminal 1"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ Terminal 2"
    port: 443
    path: /tty2
    user: root
    host: rhel
